# -*- coding: utf-8 -*-
"""HW 0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16-7cQOS3-A0MsZ7QwsdhpsHtjDl4RzWG
"""

b = 5
print(b, type(b))

b = float(b)
print (b, type(b))

b = str(b)
print (b, type(b))